name: Latest blog post workflow
# on:
#   schedule:
#     # Runs every hour
#     - cron: '0 * * * *'
on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run workflow manually'
        required: false
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@dipakrasal2009'
